name: EssentialServer
author: RTGTeam
description: People has been dreaming for ages, now its a reality!
version: 1.0.1
main: EssentialServer\Main
api: [2.0.0, 2.1.0]
commands:
  ops:
    usage: "/ops"
    permission: essentialops
  ipfind:
    usage: "/ipfind <player>"
    permission: essentialipfind
  mypos:
    usage: "/mypos"
    permission: essentialpos
  locfind:
    usage: "/locfind <player>"
    permission: essentiallocfinder
  clearinv:
    usage: "/clearinv <player>"
    permission: essentialclearinv
  heal:
    usage: "/heal <name>"
    permission: essentialheal
  afk:
    usage: "/afk <name>"
    permission: essentialafk
  lastpos:
    usage: "/lastpos"
    permission: essentiallastpos
  hub:
    usage: "/hub"
    permission: essentialhub
permissions:
  essentialops:
    default: op
  essentialipfind:
    default: op
  essentialpos:
    default: op
  essentiallocfinder:
    default: op
  essentialclearinv:
    default: op
  essentialhub:
    default: op
  essentiallastpos:
    default: op
  essentialheal:
    default: op
  essentialafk:
   default: op
