name: EssentialServer
author: RTGTeam
description: People has been dreaming for ages, now its a reality!
version: 1.0.2
main: EssentialServer\Main
api: [2.0.0, 2.1.0]
commands:
  ops:
    usage: "/ops"
    permission: essentialops
  ipfind:
    usage: "/ipfind <player>"
    permission: essentialipfind
  mypos:
    usage: "/mypos"
    permission: essentialpos
  locfind:
    usage: "/locfind <player>"
    permission: essentiallocfinder
  clearinv:
    usage: "/clearinv <player>"
    permission: essentialclearinv
  nick:
    usage: "/nick < off | set | set <player>"
    permission: essentialnick
permissions:
  essentialops:
    default: op
  essentialipfind:
    default: op
  essentialpos:
    default: op
  essentiallocfinder:
    default: op
  essentialclearinv:
    default: op
  essentialnick:
    default: op
